runtime: python38  

automatic_scaling:
   max_instances: 1

env_variables:
  BUCKET_NAME: "mawaru"  
  CLOUD_FUNCTION_URL: "https://us-central1-potatoe-disease-identification.cloudfunctions.net/predict"